lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "defusedxml"
version = "0.7.1"

[[packages.wheels]]
name = "defusedxml-0.7.1-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61"

[[packages]]
name = "packaging"
version = "26.0"

[[packages.wheels]]
name = "packaging-26.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b7/b9/c538f279a4e237a006a2c98387d081e9eb060d203d8ed34467cc0f0b9b53/packaging-26.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b36f1fef9334a5588b4166f8bcd26a14e521f2b55e6b9de3aaa80d3ff7a37529"

[[packages]]
name = "pillow"
version = "12.1.0"

[[packages.wheels]]
name = "pillow-12.1.0-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/1c/af/f23697f587ac5f9095d67e31b81c95c0249cd461a9798a061ed6709b09b5/pillow-12.1.0-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "4f9f6a650743f0ddee5593ac9e954ba1bdbc5e150bc066586d4f26127853ab94"

[[packages]]
name = "pillow-heif"
version = "1.2.0"

[[packages.wheels]]
name = "pillow_heif-1.2.0-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/51/ea/1e6e16e589ebb9e59a3c0624eecf817f6b6d9f385e0d0c5ab00bbddf0d21/pillow_heif-1.2.0-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "6b03babd6da615f0e34be62a049f46a1d8a0203d5fafeecd68acd962b5397fab"

[[packages]]
name = "pillow-jxl-plugin"
version = "1.3.7"

[[packages.wheels]]
name = "pillow_jxl_plugin-1.3.7-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/86/34/c42f2899a6d93666b2245cfef1776f464773728dc4b63c37ed232a0fe75d/pillow_jxl_plugin-1.3.7-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "2809d64c7c91546a82871933990e1c12304e8cc94a86f221bfa43ef53a91bc4d"

[[packages]]
name = "pygame-ce"
version = "2.5.6"

[[packages.wheels]]
name = "pygame_ce-2.5.6-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/87/1b/d9f180e142273dcef180ad3274213eba13ad76f335434979e584fbd57278/pygame_ce-2.5.6-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "9579c4283fd644798632aac20d65282a2e7efcdf0f79b7c545fdeda372381e30"

[[packages]]
name = "pyperclip"
version = "1.11.0"

[[packages.wheels]]
name = "pyperclip-1.11.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/df/80/fc9d01d5ed37ba4c42ca2b55b4339ae6e200b456be3a1aaddf4a9fa99b8c/pyperclip-1.11.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "299403e9ff44581cb9ba2ffeed69c7aa96a008622ad0c46cb575ca75b5b84273"

[[packages]]
name = "pyyaml"
version = "6.0.3"

[[packages.wheels]]
name = "pyyaml-6.0.3-cp314-cp314-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/23/20/bb6982b26a40bb43951265ba29d4c246ef0ff59c9fdcdf0ed04e0687de4d/pyyaml-6.0.3-cp314-cp314-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "4a2e8cebe2ff6ab7d1050ecd59c25d4c8bd7e6f400f5f82b96557ac0abafd0ac"

[[packages]]
name = "tkinterdnd2"
version = "0.4.3"

[[packages.wheels]]
name = "tkinterdnd2-0.4.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/08/c3/e04f004a53c00dc01126b6f998264cef672c6883c36aa4bd65845a8eb4c0/tkinterdnd2-0.4.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8804f5d2e2a99713ec93e85384397fec6bf66fdf2065e3750938d55018971c4a"
