lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "defusedxml"
version = "0.7.1"

[[packages.wheels]]
name = "defusedxml-0.7.1-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61"

[[packages]]
name = "packaging"
version = "25.0"

[[packages.wheels]]
name = "packaging-25.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "29572ef2b1f17581046b3a2227d5c611fb25ec70ca1ba8554b24b0e69331a484"

[[packages]]
name = "pillow"
version = "12.1.0"

[[packages.wheels]]
name = "pillow-12.1.0-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/e5/07/74a9d941fa45c90a0d9465098fe1ec85de3e2afbdc15cc4766622d516056/pillow-12.1.0-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "461f9dfdafa394c59cd6d818bdfdbab4028b83b02caadaff0ffd433faf4c9a7a"

[[packages]]
name = "pillow-heif"
version = "1.1.1"

[[packages.wheels]]
name = "pillow_heif-1.1.1-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/dd/0b/a559ad48a5c03db5ecdc7c8b8dd04df3cb1072c0f983bcaebd26e1e63442/pillow_heif-1.1.1-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "ff158ff338082d39864abd31c69ae2ee57de3f193c85ccbe365f4d7260712229"

[[packages]]
name = "pillow-jxl-plugin"
version = "1.3.7"

[[packages.wheels]]
name = "pillow_jxl_plugin-1.3.7-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/4d/02/c663f0a38fd8358ae6bc58cfcdd9bc2ba0e22d2e38b0cbe8c528b0cd2e33/pillow_jxl_plugin-1.3.7-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "23aca25bea7fc63e0466ceba12e6ddb26ce3685943185b7f6801c376f96832ed"

[[packages]]
name = "pygame"
version = "2.6.1"

[[packages.wheels]]
name = "pygame-2.6.1-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/7e/11/17f7f319ca91824b86557e9303e3b7a71991ef17fd45286bf47d7f0a38e6/pygame-2.6.1-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "813af4fba5d0b2cb8e58f5d95f7910295c34067dcc290d34f1be59c48bd1ea6a"

[[packages]]
name = "pyperclip"
version = "1.11.0"

[[packages.wheels]]
name = "pyperclip-1.11.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/df/80/fc9d01d5ed37ba4c42ca2b55b4339ae6e200b456be3a1aaddf4a9fa99b8c/pyperclip-1.11.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "299403e9ff44581cb9ba2ffeed69c7aa96a008622ad0c46cb575ca75b5b84273"

[[packages]]
name = "pyyaml"
version = "6.0.3"

[[packages.wheels]]
name = "pyyaml-6.0.3-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/97/c9/39d5b874e8b28845e4ec2202b5da735d0199dbe5b8fb85f91398814a9a46/pyyaml-6.0.3-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "79005a0d97d5ddabfeeea4cf676af11e647e41d81c9a7722a193022accdb6b7c"

[[packages]]
name = "tkinterdnd2"
version = "0.4.3"

[[packages.wheels]]
name = "tkinterdnd2-0.4.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/08/c3/e04f004a53c00dc01126b6f998264cef672c6883c36aa4bd65845a8eb4c0/tkinterdnd2-0.4.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8804f5d2e2a99713ec93e85384397fec6bf66fdf2065e3750938d55018971c4a"
