lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "defusedxml"
version = "0.7.1"

[[packages.wheels]]
name = "defusedxml-0.7.1-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61"

[[packages]]
name = "packaging"
version = "26.0"

[[packages.wheels]]
name = "packaging-26.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b7/b9/c538f279a4e237a006a2c98387d081e9eb060d203d8ed34467cc0f0b9b53/packaging-26.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b36f1fef9334a5588b4166f8bcd26a14e521f2b55e6b9de3aaa80d3ff7a37529"

[[packages]]
name = "pillow"
version = "12.0.0"

[[packages.wheels]]
name = "pillow-12.0.0-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/6d/2a/dd43dcfd6dae9b6a49ee28a8eedb98c7d5ff2de94a5d834565164667b97b/pillow-12.0.0-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "4cf7fed4b4580601c4345ceb5d4cbf5a980d030fd5ad07c4d2ec589f95f09905"

[[packages]]
name = "pillow-avif-plugin"
version = "1.5.2"

[[packages.wheels]]
name = "pillow_avif_plugin-1.5.2-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/4d/40/f11c63a815bae18b4792df5435e61351d90cc4795da5cb4e19b1d4bf532e/pillow_avif_plugin-1.5.2-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "b840a431dbb04f60a18bbd2e28c2b26d845efcddd28f98e9386eb5a5938a3b38"

[[packages]]
name = "pillow-heif"
version = "1.2.0"

[[packages.wheels]]
name = "pillow_heif-1.2.0-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/63/0b/cb85f3c416c6734464ef5a3c40936256b9eb3ef7789698ca11fde102a508/pillow_heif-1.2.0-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "c28144e24bc8413c61f48a7887a6545aa3be59d3011b7fb22c315d2192a39ea6"

[[packages]]
name = "pillow-jxl-plugin"
version = "1.3.7"

[[packages.wheels]]
name = "pillow_jxl_plugin-1.3.7-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/4d/02/c663f0a38fd8358ae6bc58cfcdd9bc2ba0e22d2e38b0cbe8c528b0cd2e33/pillow_jxl_plugin-1.3.7-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "23aca25bea7fc63e0466ceba12e6ddb26ce3685943185b7f6801c376f96832ed"

[[packages]]
name = "pygame-ce"
version = "2.5.6"

[[packages.wheels]]
name = "pygame_ce-2.5.6-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/2d/d9/1d16eff301bda4b22d1d19eda966cfbc9bf174648e4af85dee8c5ffb72cf/pygame_ce-2.5.6-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "c38f17313b27ad97f0578ba863972b6e1fe22b1ec8568af6c7785b5bd55d21e1"

[[packages]]
name = "pyperclip"
version = "1.11.0"

[[packages.wheels]]
name = "pyperclip-1.11.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/df/80/fc9d01d5ed37ba4c42ca2b55b4339ae6e200b456be3a1aaddf4a9fa99b8c/pyperclip-1.11.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "299403e9ff44581cb9ba2ffeed69c7aa96a008622ad0c46cb575ca75b5b84273"

[[packages]]
name = "pyyaml"
version = "6.0.3"

[[packages.wheels]]
name = "pyyaml-6.0.3-cp313-cp313-win_amd64.whl"
url = "https://files.pythonhosted.org/packages/97/c9/39d5b874e8b28845e4ec2202b5da735d0199dbe5b8fb85f91398814a9a46/pyyaml-6.0.3-cp313-cp313-win_amd64.whl"

[packages.wheels.hashes]
sha256 = "79005a0d97d5ddabfeeea4cf676af11e647e41d81c9a7722a193022accdb6b7c"

[[packages]]
name = "tkinterdnd2"
version = "0.4.3"

[[packages.wheels]]
name = "tkinterdnd2-0.4.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/08/c3/e04f004a53c00dc01126b6f998264cef672c6883c36aa4bd65845a8eb4c0/tkinterdnd2-0.4.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8804f5d2e2a99713ec93e85384397fec6bf66fdf2065e3750938d55018971c4a"
